### ISSUE TITLE
Please tag releases in Git

### ISSUE THREAD

**Issue by merkys** [wojdyr/debyer#3]
Some source files cite Debyer version (0.4 at the time of posting). However, without Git tags it is difficult to find the commit corresponding to Debyer 0.4 release, as well as to download the source of this precise version.

**Comment by wojdyr** [comment]
OK. If there is ever a new release of debyer I'll tag it.

**Comment by merkys** [comment]
Thanks. What about a tag for v0.4?

**Comment by wojdyr** [comment]
Hard to tell where exactly it should be tagged. This code almost hasn't changed for 10 or more years, so I wouldn't worry about versions.
Some of the past tarballs are here:
https://code.google.com/archive/p/debyer/downloads

**Comment by merkys** [comment]
Thanks for the link.
